### ISSUE TITLE
Install simpleanalytics script code into site editing Jekyll layout file

### ISSUE THREAD

**Issue by anotherpatrickcollins** [codefordenver/dearneighbors#3]
Add these two lines at the end of the body tag, right before the closing body tag

```
<script async defer src="https://cdn.simpleanalytics.io/hello.js"></script>
<noscript><img src="https://api.simpleanalytics.io/hello.gif" alt=""></noscript>
```

>     Layouts
> 
>     If you'd like to change the theme's HTML layout:
> 
>     Copy the original template from the theme's repository
>     (Pro-tip: click "raw" to make copying easier)
>     Create a file called /_layouts/default.html in your site
>     Paste the default layout content copied in the first step
>     Customize the layout as you'd like

**Comment by jberns** [comment]
This is done!
