### ISSUE TITLE
Add ID for tracking

### ISSUE THREAD

**Issue by anotherpatrickcollins** [codefordenver/dearneighbors#6]
Add ID to the screenshot download trigger so Simpleanalytics can track the event.

**Comment by anotherpatrickcollins** [comment]
Addressed by #12

**Comment by anotherpatrickcollins** [comment]
@jberns the id for the image download is "download-dear-neighbors-pdf-png" 

See if that works, I put the ID on the image, but it might need to be on the link now that I think about it.

**Comment by jberns** [comment]
Looks like it is working!
